Update for hyper 0.12
ferristseng/rust-multipart-rfc7578 pull request #3
Opened 2018-06-25 01:37 UTC by asonix

Also updates Rand dependency, and moves from tokio-core to tokio for examples. It also uses Hyper's provided body type as a wrapper around the multipart body stream.

2018-06-25 01:38 UTC, asonix commented
There's definitely some cleaning that can be done, especially since there's no concept of a custom client anymore.

2018-06-25 15:00 UTC, ferristseng commented
Thanks your for this!

I am going to take a look at the new Hyper changes before I merge this!

2018-06-26 01:51 UTC, ferristseng requested changes
Hey, these changes look awesome! There were a couple of minor things that I commented on, but otherwise it looks good to go. Thanks for the help!

2018-06-26 01:51 UTC, ferristseng commented on src/error.rs
> +            Error::ContentRead(_) => "Error reading content: {}",
Remove the `: {}` for these error messages.

2018-06-26 01:51 UTC, ferristseng commented on src/client_.rs
> +            ),
As opposed to having the header name be in the variable for `content_disposition` and `content_type`, what do you think about just writing the header names in the `write_headers` function?

Also a little bit disappointed that those types were removed.

2018-06-26 17:23 UTC, merged